org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=HyLobby
mod_id=hylobby
mod_version=0.0.0
mod_description=Minecraft mod for Hypixel adding lobby related features like middle click gui items and sound silencer
mod_archives_name=HyLobby
base_group=tomeko.hylobby

java_version=[VERSIONED]
minecraft_version=[VERSIONED]

fabric_loader_version=0.19.5
fabric_api_version=[VERSIONED]
osl_version=0.21.0

oneconfig_version=[VERSIONED]
hypixel_mod_api_version=[VERSIONED]
mod_menu_version=[VERSIONED]

stonecutter_version=0.10-alpha.8